name: 'Install Dependencies'
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
jobs:
    install:
        name: 'Install and Cache PowerShell Modules'
        runs-on: windows-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v3
            - name: 'Install Modules'
              uses: potatoqualitee/psmodulecache@v5.2
              with:
                modules_to_cache: InvokeBuild
