name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Docs/Website/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy MkDocs
        run: |
          cd Docs/Website/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdocs gh-deploy --force
