name: Publish Module
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: PSGallery
        id: psgallery
        shell: pwsh
        run: |
          $apiKey = ${{ secrets.PS_GALLERY_API_KEY }} | ConvertTo-SecureString -AsPlainText -Force
          $cred = [pscredential]::new('apikey', $apiKey)
          ./build.ps1 -Task Publish -PSGalleryApiKey $cred -Bootstrap

      - name: GitHub
        id: ghpkg
        shell: pwsh
        run: |
          $apiKey = ${{ secrets.GITHUB_TOKEN }} | ConvertTo-SecureString -AsPlainText -Force
          $cred = [pscredential]::new('apikey', $apiKey)
          ./build.ps1 -Task Publish -GitHubApiKey $cred -Bootstrap
